# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
## Environment Properties
# You can find the latest Forge versions here: https://files.minecraftforge.net/net/minecraftforge/forge/
minecraft_version=1.20.1
# The Minecraft version range can use any release version of Minecraft as bounds.
# Snapshots, pre-releases, and release candidates are not guaranteed to sort properly
# as they do not follow standard versioning conventions.
minecraft_version_range=[1.20.1,1.20.2)
# The Forge version must agree with the Minecraft version to get a valid artifact.
forge_version=47.3.0
forge_version_range=[47,)
# The loader version range can only use the major version of FML as bounds
loader_version_range=[47,)
parchment_minecraft_version=1.20.1
parchment_mappings_version=2023.09.03
jei_version=15.20.0.106
jade_version=11.13.2+forge
kubejs_version=2001.6.5-build.16+forge
rhino_version=2001.2.2-build.18+forge
## Mod Properties
# The unique mod identifier for the mod. Must be lowercase in English locale. Must fit the regex [a-z][a-z0-9_]{1,63}
# Must match the String constant located in the main mod class annotated with @Mod.
mod_id=skyresources
# The human-readable display name for the mod.
mod_name=SkyResources3
mod_loader=forge
# The license of the mod. Review your options at https://choosealicense.com/. All Rights Reserved is the default.
mod_license=MIT
# The mod version. See https://semver.org/
mod_version=1.0.0
mod_version_tag=release
# The group ID for the mod. It is only important when publishing as an artifact to a Maven repository.
# This should match the base package used for the mod sources.
# See https://maven.apache.org/guides/mini/guide-naming-conventions.html
mod_group_id=committee.nova.mods
# The authors of the mod. This is a simple text string that is used for display purposes in the mod list.
mod_authors=cnlimiter
# The description of the mod. This is a simple multiline text string that is used for display purposes in the mod list.
mod_description=The ultimate companion skyblock mod supporting a ton of other mods! Obtain everything from nearly nothing.
